language: java

matrix:
  include:
    - os: linux
      language: android
      jdk: oraclejdk8 
      android:
        components:
        - tools
        - android-26
        - platform-tools
        - build-tools-26.0.2
    - os: osx
      osx_image: xcode9.1
      before_install:
      - brew install gradle
      - chmod +x gradlew
      
      
     
        

script:
- ./gradlew assemble
- ./gradlew :api:check
- ./gradlew :safe-app:check
- ./gradlew :safe-app-android:check
      
 
     
