language: java
matrix:
  include:
    - os: linux
      language: android
      jdk: oraclejdk8 
      android:
        components:
        - tools
        - android-26
        - platform-tools
        - build-tools-26.0.2
    - os: osx
      osx_image: xcode9.1
      before_install:
      - ${ANDROID_HOME}tools/bin/sdkmanager --channel=3 \
  "tools" "platform-tools" "build-tools;26.0.2-rc2" "platforms;android-O" \
  "extras;google;google_play_services"
      - chmod +x gradlew
      
   
script:
- chmod +x gradlew
- ./gradlew :api:check
- ./gradlew :safe-app:check
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew :safe-app-android:check; fi

      
 
     
