language: java
matrix:
  include:
    - os: linux
      language: android
      jdk: oraclejdk8 
      android:
        components:
        - tools
        - android-26
        - platform-tools
        - build-tools-26.0.2
    - os: osx
      osx_image: xcode9.1
      before_install:
      - brew install gradle
      - export ANDROID_HOME=$HOME/.android
      - mkdir -p $HOME/.android    
      - mkdir "$ANDROID_HOME/licenses"
      - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
      - chmod +x gradlew
      
   
script:
- chmod +x gradlew
- ./gradlew :api:check
- ./gradlew :safe-app:check
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew :safe-app-android:check; fi

      
 
     
