build : false

install:
      - chmod +x gradlew
      - export ANDROID_HOME=$HOME/.android
      - mkdir -p $HOME/.android    
      - mkdir -p $ANDROID_HOME/licenses
      - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
      - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
 
test_script:
 - gradlew.bat :api:check
 - gradlew.bat :safe-app:check
 

cache:
  - .gradle
  - C:\Users\appveyor\.gradle
  
